#!/usr/bin/env bash

set -e
cd build

project=6
format=0
help() {
  echo "hello world"
}

while [[ $# -gt 0 ]]; do
  case $1 in
    -p|--project)
      project=$2
      ;;
    -f|--format)
      format=$2
      ;;
  esac
  shift
  shift
done

if [[ $format -ne 0 ]]; then
  echo "$ make format"
  make format
  echo "$ make check-lint"
  make check-lint
  echo "$ make check-clang-tidy"
  make check-clang-tidy
fi

if [[ $project -lt 0 || $project -gt 5 ]]; then
  help
elif [[ $project -eq 0 ]]; then
  make starter_test
  ./test/starter_test
elif [[ $project -eq 1 ]]; then
  make grading_clock_replacer_test
  make grading_buffer_pool_manager_test
  make grading_buffer_pool_manager_concurrency_test
  ./test/grading_clock_replacer_test
  ./test/grading_buffer_pool_manager_test
  ./test/grading_buffer_pool_manager_concurrency_test
elif [[ $project -eq 2 ]]; then
  make grading_b_plus_tree_checkpoint_1_test
  ./test/grading_b_plus_tree_checkpoint_1_test
elif [[ $project -eq 3 ]]; then
  make grading_b_plus_tree_checkpoint_2_concurrent_test
  make grading_b_plus_tree_checkpoint_2_sequential_test
  ./test/grading_b_plus_tree_checkpoint_2_concurrent_test
  ./test/grading_b_plus_tree_checkpoint_2_sequential_test
elif [[ $project -eq 4 ]]; then
  make grading_catalog_test
  make grading_executor_test
  ./test/grading_catalog_test
  ./test/grading_executor_test
elif [[ $project -eq 5]]; then
  make rollback_test
  make grading_transaction_test
  make grading_lock_manager_detection_test
  make grading_lock_manager_test_1
  make grading_lock_manager_test_2
  make grading_lock_manager_test_3
  ./test/rollback_test
  ./test/grading_transaction_test
  ./test/grading_lock_manager_detection_test
  ./test/grading_lock_manager_test_1
  ./test/grading_lock_manager_test_2
  ./test/grading_lock_manager_test_3
fi
