#!/usr/bin/env bash

cd build

echo "$ make format"
make format
if [[ $? -ne 0 ]]; then
    echo "make format error!"
    exit 1
fi

echo "$ make check-lint"
make check-lint
if [[ $? -ne 0 ]]; then
    echo "make check-lint error!"
    exit 1
fi

echo "make check-clang-tidy"
make check-clang-tidy
if [[ $? -ne 0 ]]; then
    echo "make check-clang-tidy error!"
    exit 1
fi
